# Generated by Django 5.2.5 on 2025-08-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('users', '0002_alter_profile_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='musicians', to='instruments.instrument'),
        ),
    ]
