# Generated by Django 5.2.4 on 2025-08-01 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=30)),
                ('name', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('birthdate', models.DateField()),
                ('instruments', models.ManyToManyField(to='rooms.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_description', models.TextField(blank=True)),
                ('privacy', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], default='publica', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('url_jitsi', models.URLField(blank=True)),
                ('required_instruments', models.ManyToManyField(blank=True, to='rooms.instrument')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_creadas', to='rooms.user')),
            ],
        ),
    ]
