# Generated by Django 5.2.4 on 2025-08-17 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('rooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='instruments',
        ),
        migrations.AlterField(
            model_name='room',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_creadas', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='required_instruments',
            field=models.ManyToManyField(blank=True, to='instruments.instrument'),
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
